version: '3.9'

services:
  quote-app:
    container_name: quote_app_db
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: db_adminer
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080

  # mongo:
  #   container_name: mongo_db
  #   image: mongo:4.4.19-rc0-focal
  #   volumes:
  #     - ./mongo_data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - ${MONGO_PORT}:27017

  # mongo-express:
  #   container_name: db_express
  #   image: mongo-express
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_EXPRESS_ADMINUSERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_EXPRESS_ADMINPASSWORD}
  #     ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
  #     ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_EXPRESS_USERNAME}
  #     ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_EXPRESS_PASSWORD}
  #   ports:
  #     - ${MONGODB_EXPRESS_PORT}:8081

volumes:
  postgres_data:
  # mongo_data:
